global using Application.Abstractions.Services;
global using Infrastructure.Services;
global using Microsoft.Extensions.DependencyInjection;
global using System.Net.Sockets;
global using Domain.Enums;
global using Application.Network.Interaction;
global using System.Text;
global using System.Net;
global using Domain.Constants;
